### ISSUE TITLE
PCB to Germany

### ISSUE THREAD

**Issue by TheZoker** [klaasnicolaas/ha_nfc_scanner#1]
Awesome NFC project! 
I know not really an issue, but the best way to contact you

Just wondering if you would also send these PCBs that you made to Germany? 😃

**Comment by klaasnicolaas** [comment]
You can contact me directly via Discord (Mister Nicolaz#7558), [Twitter](https://twitter.com/klaasnicolaas) or email (on my Github profile).

Then we will see what is possible.
